\ProvidesClass{datainlogistics}

\LoadClass{article}

\usepackage{everypage}
\usepackage[pages=all, placement=top, opacity=1, scale=1]{background}

\backgroundsetup{
contents={%
  \includegraphics[width=\paperwidth,height=\paperheight]{dil_background.pdf}
  }%
}

\renewcommand{\familydefault}{\sfdefault}
\setlength\parskip{\medskipamount}
\setlength\parindent{0pt}
\usepackage{hyperref}
\hypersetup{colorlinks=true,linkcolor=blue}
